// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Brahma.Helpers")]
[assembly: AssemblyProductAttribute("Brahma.FSharp")]
[assembly: AssemblyDescriptionAttribute("F# quotation to OpenCL translator.")]
[assembly: AssemblyVersionAttribute("1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.0";
        internal const string InformationalVersion = "1.0.0";
    }
}
