// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Brahma.OpenCL")]
[assembly: AssemblyProductAttribute("Brahma.FSharp")]
[assembly: AssemblyDescriptionAttribute("F# quotation to OpenCL translator.")]
[assembly: AssemblyVersionAttribute("1.0.1")]
[assembly: AssemblyFileVersionAttribute("1.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.1";
        internal const string InformationalVersion = "1.0.1";
    }
}
